# Generated by Django 3.1.4 on 2020-12-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answers_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['date_posted']},
        ),
    ]
