# Generated by Django 3.1.4 on 2020-12-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20201218_1754'),
        ('forum', '0003_auto_20201217_1743'),
    ]

    operations = [
    ]
